version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: akeneo_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: akeneo_pim
      MYSQL_USER: akeneo
      MYSQL_PASSWORD: akeneo
    volumes:
      - db_data:/var/lib/mysql
    restart: unless-stopped

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.17
    container_name: akeneo_elasticsearch
    environment:
      discovery.type: single-node
      cluster.name: akeneo
      xpack.security.enabled: "false"
      bootstrap.memory_lock: "true"
      ES_JAVA_OPTS: -Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es_data:/usr/share/elasticsearch/data
    restart: unless-stopped

  akeneo_php:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: akeneo_php
    depends_on:
      - db
      - elasticsearch
    volumes:
      - ak_data:/var/www/html
    environment:
      APP_ENV: dev
      APP_DEBUG: 1
      DATABASE_URL: mysql://akeneo_pim:akeneo_pim@db:3306/akeneo_pim
      ELASTICSEARCH_HOSTS: 'elasticsearch:9200'
    ports:
      - "8081:80"
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: akeneo_nginx
    depends_on:
      - akeneo_php
    ports:
      - "8082:80"
    volumes:
      - ./docker/nginx:/etc/nginx:ro
      - .:/var/www/html

volumes:
  db_data:
  es_data:
  ak_data:
