version: "3.8"

services:
  db:
    image: mysql:8.0
    container_name: akeneo-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: akeneo_pim
      MYSQL_USER: akeneo
      MYSQL_PASSWORD: akeneo
    volumes:
      - dbdata:/var/lib/mysql
    restart: unless-stopped

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.17
    container_name: akeneo-es
    environment:
      discovery.type: single-node
      xpack.security.enabled: "false"
      bootstrap.memory_lock: "true"
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data
    restart: unless-stopped

  akeneo:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: akeneo
    depends_on:
      - db
      - elasticsearch
    volumes:
      - .:/var/www/html
    environment:
      APP_ENV: dev
      DATABASE_URL: mysql://akeneo:akeneo@db:3306/akeneo_pim
      ELASTICSEARCH_HOSTS: 'elasticsearch:9200'
    ports:
      - "8081:80"
    restart: unless-stopped

volumes:
  dbdata:
  esdata:
